/*
 * ev_io_define.h
 *
 *  Created on: Nov 9, 2025
 *      Author: Admin
 */

#ifndef EV_IO_HANDLE_EV_IO_DEFINE_H_
#define EV_IO_HANDLE_EV_IO_DEFINE_H_

#include "sm_types.h"

#define SM_IO_CMD_SUCCESS   (0)
#define SM_IO_CMD_FAILURE   (-1)

#define SM_IO_CMD_TIMEOUT   1000

enum {

	SM_IOC_IO_EVENT_HORN_CHANGED,

    SM_IOC_IO_EVENT_LEFT_CHANGED,
    SM_IOC_IO_EVENT_RIGHT_CHANGED,
    SM_IOC_IO_EVENT_EMERGENCY_CHANGED,

    SM_IOC_IO_EVENT_PHASE_CHANGED,
    SM_IOC_IO_EVENT_COS_CHANGED,
    SM_IOC_IO_EVENT_POS_CHANGED,

	SM_IOC_IO_EVENT_FIND_VEHICLE_MODE_CHANGED,
	SM_IOC_IO_EVENT_CTRL_KEY_CHANGED,
    SM_IOC_IO_EVENT_LOCK_MODE_CHANGED,
    SM_IOC_IO_EVENT_BLOCK_MODE_CHANGED,
    SM_IOC_IO_EVENT_ANTI_THEFT_MODE_CHANGED,

    SM_IOC_IO_EVENT_MC_POWER_CHANGED,
    SM_IOC_IO_EVENT_CHARGER_CHANGED,

    SM_IOC_IO_EVENT_NUMBER
};

enum {

	SM_PMU_IO_EVENT_12V_CHANGED,
    SM_PMU_IO_EVENT_NUMBER
};

enum {
    IO_INACTIVE = 0,
	IO_ACTIVE,
	IO_BLINK
};

#endif /* EV_IO_HANDLE_EV_IO_DEFINE_H_ */
